default: &default
  host: localhost
  user: postgres
  password: ''
  adapter: postgres

development:
  <<: *default
  db: agentc_app_template_oss_development

test:
  <<: *default
  db: agentc_app_template_oss_test

production:
  <<: *default
  db: agentc_app_template_oss_production